// LOCALHOST
### Get all contacts
GET http://localhost:8080/contacts

### Get contact by ID
GET http://localhost:8080/contacts/667ff148fca0f7959f0c37cc

### Create contact
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json
{
    "firstName": "Frodo",
    "lastName": "Baggins",
    "email": "frodo@baggins.shire",
    "favoriteColor": "gold",
    "birthday": "09/22/1368"
}

### PUT contact - under construction
#PUT http://localhost:8080/contacts/667ff148fca0f7959f0c37cc HTTP/1.1
#content-type: application/json
#{
#    "firstName": "Samwise",\n    "lastName": "Gamgee",\n    "email": "samwise@gamgee.bagend",\n    "favoriteColor": "green",\n    "birthday": "04/06/1380"
#}

### Delete contact - under construction
#DELETE http://localhost:8080/contacts/667ff148fca0f7959f0c37cc HTTP/1.1



// PRODUCTION
### Get all contacts
GET https://cse341-contacts-53a7.onrender.com/contacts

### Get contact by ID
GET https://cse341-contacts-53a7.onrender.com/contacts/667ff148fca0f7959f0c37cc

### Create contact
POST https://cse341-contacts-53a7.onrender.com/contacts HTTP/1.1
content-type: application/json
{
    "firstName": "Frodo",
    "lastName": "Baggins",
    "email": "frodo@baggins.shire",
    "favoriteColor": "gold",
    "birthday": "09/22/1368"
}

### PUT contact - under construction
#PUT https://cse341-contacts-53a7.onrender.com/contacts/667ff148fca0f7959f0c37cc HTTP/1.1
#content-type: application/json
#{
#    "firstName": "Samwise",\n    "lastName": "Gamgee",\n    "email": "samwise@gamgee.bagend",\n    "favoriteColor": "green",\n    "birthday": "04/06/1380"
#}

### Delete contact - under construction
#DELETE https://cse341-contacts-53a7.onrender.com/contacts/667ff148fca0f7959f0c37cc HTTP/1.1